//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Case_Detials_History
    {
        public int ACDH_ID { get; set; }
        public int ACDH_ACD_ID { get; set; }
        public string ACDH_HspAccID { get; set; }
        public string ACDH_Amount { get; set; }
        public string ACDH_Status { get; set; }
        public string ACDH_Owner { get; set; }
        public string ACDH_Type { get; set; }
        public string ACDH_SubType { get; set; }
        public string ACDH_PayerReason { get; set; }
        public string ACDH_PrimaryReason { get; set; }
        public string ACDH_SecondaryReason { get; set; }
        public string ACDH_PrinDiag { get; set; }
        public string ACDH_PrinProc { get; set; }
        public string ACDH_Comments { get; set; }
        public string ACDH_CreatedBy { get; set; }
        public System.DateTime ACDH_CreatedDate { get; set; }
        public string ACDH_UpdatedBy_DB { get; set; }
    
        public virtual Account_Case_Details Account_Case_Details { get; set; }
    }
}
