//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denials_Data
    {
        public string Invoice { get; set; }
        public string Ext_Rsn_Code { get; set; }
        public int Ln_on_EOB { get; set; }
        public Nullable<int> Rev_Code { get; set; }
        public string CPT_R_Code { get; set; }
        public string Allowed_Amt { get; set; }
        public string Denied_Amount { get; set; }
        public string Billed_Amount { get; set; }
        public string Bucket_Payor { get; set; }
        public string Bucket_Plan { get; set; }
        public string Aging_Bkt { get; set; }
        public string Owning_Area { get; set; }
        public string Source_Area { get; set; }
        public string Status { get; set; }
        public string Root_Cause { get; set; }
        public string Preventable { get; set; }
        public string Follow_Up_Date { get; set; }
        public string Resolution_or_Resp_Cat { get; set; }
        public string Rcvd_Dt { get; set; }
        public string Acct_Class { get; set; }
        public long Account_ID { get; set; }
        public string Account_Name { get; set; }
        public string Account_Location { get; set; }
        public Nullable<int> Follow_up_ID { get; set; }
        public string First_Payor_Rcvd_Dt { get; set; }
        public string Last_Payor_Rcvd_Dt { get; set; }
        public string Days_Denied { get; set; }
        public string Denial_Cat { get; set; }
        public string Ext_Rsn_Code_w__Desc { get; set; }
        public string First_Claim_Dt { get; set; }
        public string HB_Acct_Bal { get; set; }
        public string Acct_Status { get; set; }
        public string Paid_Amount { get; set; }
        public Nullable<System.DateTime> Last_Reopened_Date { get; set; }
        public string Last_User_for_Closed_Rec { get; set; }
        public Nullable<System.DateTime> Last_Completed_Date { get; set; }
        public string Rsn_Code { get; set; }
        public string Reporting_Rsn_Code_w_Desc { get; set; }
        public string Service_Area { get; set; }
        public string Rev_Code_Desc { get; set; }
        public string Source { get; set; }
        public string Source_Dept { get; set; }
        public Nullable<long> Stage { get; set; }
        public int Age { get; set; }
        public string Clinical_Root_Cause { get; set; }
        public string Financial_Class { get; set; }
        public Nullable<System.DateTime> First_Ext_Claim_Sent_Date { get; set; }
        public string Src_Pmt_Tx { get; set; }
    }
}
