//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareAnalytics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TCG_DataEntities : DbContext
    {
        public TCG_DataEntities()
            : base("name=TCG_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users_Data> Users_Data { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
    
        public virtual ObjectResult<Get_Account_Info_for_ARandDenial_Result> Get_Account_Info_for_ARandDenial(string account_ID)
        {
            var account_IDParameter = account_ID != null ?
                new ObjectParameter("Account_ID", account_ID) :
                new ObjectParameter("Account_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Account_Info_for_ARandDenial_Result>("Get_Account_Info_for_ARandDenial", account_IDParameter);
        }
    
        public virtual ObjectResult<Get_AR_Info_for_Balance_Range_Result> Get_AR_Info_for_Balance_Range(Nullable<int> varBalanceRange)
        {
            var varBalanceRangeParameter = varBalanceRange.HasValue ?
                new ObjectParameter("varBalanceRange", varBalanceRange) :
                new ObjectParameter("varBalanceRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_AR_Info_for_Balance_Range_Result>("Get_AR_Info_for_Balance_Range", varBalanceRangeParameter);
        }
    
        public virtual int registration(string first_name, string last_name, string middle_name, string email, string phone_number, string pwd)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registration", first_nameParameter, last_nameParameter, middle_nameParameter, emailParameter, phone_numberParameter, pwdParameter);
        }
    
        public virtual int CreateAccount(string first_name, string last_name, string middle_name, string email, string phone_number, string pwd)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAccount", first_nameParameter, last_nameParameter, middle_nameParameter, emailParameter, phone_numberParameter, pwdParameter);
        }
    
        public virtual int Case_Task_InsUpd(Nullable<int> accCase_ID, Nullable<int> accTsk_ID, string accCase_HspAccID, string accCase_Amount, string accCase_Status, string accCase_Owner, string accCase_Type, string accCase_SubType, string accCase_PayerReason, string accCase_PrimaryReason, string accCase_SecondaryReason, string accCase_PrinDiag, string accCase_PrinProc, string accCase_Comments, Nullable<int> accTsk_AccCase_ID, string accTsk_Completed, string accTsk_Priority, string accTsk_Description, string accTsk_Owner, string accTsk_Comment, Nullable<System.DateTime> accTsk_DueDate, string accTsk_CreatedBy_User, Nullable<System.DateTime> accTsk_CreatedDate, string accTsk_UpdatedBy_User, Nullable<System.DateTime> accTsk_Updateddate, string accTsk_UpdatedBy_DB, ObjectParameter new_recordNumber)
        {
            var accCase_IDParameter = accCase_ID.HasValue ?
                new ObjectParameter("AccCase_ID", accCase_ID) :
                new ObjectParameter("AccCase_ID", typeof(int));
    
            var accTsk_IDParameter = accTsk_ID.HasValue ?
                new ObjectParameter("AccTsk_ID", accTsk_ID) :
                new ObjectParameter("AccTsk_ID", typeof(int));
    
            var accCase_HspAccIDParameter = accCase_HspAccID != null ?
                new ObjectParameter("AccCase_HspAccID", accCase_HspAccID) :
                new ObjectParameter("AccCase_HspAccID", typeof(string));
    
            var accCase_AmountParameter = accCase_Amount != null ?
                new ObjectParameter("AccCase_Amount", accCase_Amount) :
                new ObjectParameter("AccCase_Amount", typeof(string));
    
            var accCase_StatusParameter = accCase_Status != null ?
                new ObjectParameter("AccCase_Status", accCase_Status) :
                new ObjectParameter("AccCase_Status", typeof(string));
    
            var accCase_OwnerParameter = accCase_Owner != null ?
                new ObjectParameter("AccCase_Owner", accCase_Owner) :
                new ObjectParameter("AccCase_Owner", typeof(string));
    
            var accCase_TypeParameter = accCase_Type != null ?
                new ObjectParameter("AccCase_Type", accCase_Type) :
                new ObjectParameter("AccCase_Type", typeof(string));
    
            var accCase_SubTypeParameter = accCase_SubType != null ?
                new ObjectParameter("AccCase_SubType", accCase_SubType) :
                new ObjectParameter("AccCase_SubType", typeof(string));
    
            var accCase_PayerReasonParameter = accCase_PayerReason != null ?
                new ObjectParameter("AccCase_PayerReason", accCase_PayerReason) :
                new ObjectParameter("AccCase_PayerReason", typeof(string));
    
            var accCase_PrimaryReasonParameter = accCase_PrimaryReason != null ?
                new ObjectParameter("AccCase_PrimaryReason", accCase_PrimaryReason) :
                new ObjectParameter("AccCase_PrimaryReason", typeof(string));
    
            var accCase_SecondaryReasonParameter = accCase_SecondaryReason != null ?
                new ObjectParameter("AccCase_SecondaryReason", accCase_SecondaryReason) :
                new ObjectParameter("AccCase_SecondaryReason", typeof(string));
    
            var accCase_PrinDiagParameter = accCase_PrinDiag != null ?
                new ObjectParameter("AccCase_PrinDiag", accCase_PrinDiag) :
                new ObjectParameter("AccCase_PrinDiag", typeof(string));
    
            var accCase_PrinProcParameter = accCase_PrinProc != null ?
                new ObjectParameter("AccCase_PrinProc", accCase_PrinProc) :
                new ObjectParameter("AccCase_PrinProc", typeof(string));
    
            var accCase_CommentsParameter = accCase_Comments != null ?
                new ObjectParameter("AccCase_Comments", accCase_Comments) :
                new ObjectParameter("AccCase_Comments", typeof(string));
    
            var accTsk_AccCase_IDParameter = accTsk_AccCase_ID.HasValue ?
                new ObjectParameter("AccTsk_AccCase_ID", accTsk_AccCase_ID) :
                new ObjectParameter("AccTsk_AccCase_ID", typeof(int));
    
            var accTsk_CompletedParameter = accTsk_Completed != null ?
                new ObjectParameter("AccTsk_Completed", accTsk_Completed) :
                new ObjectParameter("AccTsk_Completed", typeof(string));
    
            var accTsk_PriorityParameter = accTsk_Priority != null ?
                new ObjectParameter("AccTsk_Priority", accTsk_Priority) :
                new ObjectParameter("AccTsk_Priority", typeof(string));
    
            var accTsk_DescriptionParameter = accTsk_Description != null ?
                new ObjectParameter("AccTsk_Description", accTsk_Description) :
                new ObjectParameter("AccTsk_Description", typeof(string));
    
            var accTsk_OwnerParameter = accTsk_Owner != null ?
                new ObjectParameter("AccTsk_Owner", accTsk_Owner) :
                new ObjectParameter("AccTsk_Owner", typeof(string));
    
            var accTsk_CommentParameter = accTsk_Comment != null ?
                new ObjectParameter("AccTsk_Comment", accTsk_Comment) :
                new ObjectParameter("AccTsk_Comment", typeof(string));
    
            var accTsk_DueDateParameter = accTsk_DueDate.HasValue ?
                new ObjectParameter("AccTsk_DueDate", accTsk_DueDate) :
                new ObjectParameter("AccTsk_DueDate", typeof(System.DateTime));
    
            var accTsk_CreatedBy_UserParameter = accTsk_CreatedBy_User != null ?
                new ObjectParameter("AccTsk_CreatedBy_User", accTsk_CreatedBy_User) :
                new ObjectParameter("AccTsk_CreatedBy_User", typeof(string));
    
            var accTsk_CreatedDateParameter = accTsk_CreatedDate.HasValue ?
                new ObjectParameter("AccTsk_CreatedDate", accTsk_CreatedDate) :
                new ObjectParameter("AccTsk_CreatedDate", typeof(System.DateTime));
    
            var accTsk_UpdatedBy_UserParameter = accTsk_UpdatedBy_User != null ?
                new ObjectParameter("AccTsk_UpdatedBy_User", accTsk_UpdatedBy_User) :
                new ObjectParameter("AccTsk_UpdatedBy_User", typeof(string));
    
            var accTsk_UpdateddateParameter = accTsk_Updateddate.HasValue ?
                new ObjectParameter("AccTsk_Updateddate", accTsk_Updateddate) :
                new ObjectParameter("AccTsk_Updateddate", typeof(System.DateTime));
    
            var accTsk_UpdatedBy_DBParameter = accTsk_UpdatedBy_DB != null ?
                new ObjectParameter("AccTsk_UpdatedBy_DB", accTsk_UpdatedBy_DB) :
                new ObjectParameter("AccTsk_UpdatedBy_DB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Case_Task_InsUpd", accCase_IDParameter, accTsk_IDParameter, accCase_HspAccIDParameter, accCase_AmountParameter, accCase_StatusParameter, accCase_OwnerParameter, accCase_TypeParameter, accCase_SubTypeParameter, accCase_PayerReasonParameter, accCase_PrimaryReasonParameter, accCase_SecondaryReasonParameter, accCase_PrinDiagParameter, accCase_PrinProcParameter, accCase_CommentsParameter, accTsk_AccCase_IDParameter, accTsk_CompletedParameter, accTsk_PriorityParameter, accTsk_DescriptionParameter, accTsk_OwnerParameter, accTsk_CommentParameter, accTsk_DueDateParameter, accTsk_CreatedBy_UserParameter, accTsk_CreatedDateParameter, accTsk_UpdatedBy_UserParameter, accTsk_UpdateddateParameter, accTsk_UpdatedBy_DBParameter, new_recordNumber);
        }
    
        public virtual int md_notnull_to_null_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_notnull_to_null_fields", tablenameParameter);
        }
    
        public virtual int md_null_blank_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_null_blank_fields", tablenameParameter);
        }
    
        public virtual int md_null_to_NULL_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_null_to_NULL_fields", tablenameParameter);
        }
    }
}
