//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareAnalytics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TCG_DataEntities : DbContext
    {
        public TCG_DataEntities()
            : base("name=TCG_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
        public virtual DbSet<Users_Data> Users_Data { get; set; }
        public virtual DbSet<Denials_Data> Denials_Data { get; set; }
    
        public virtual ObjectResult<Get_Account_Info_for_ARandDenial_Result> Get_Account_Info_for_ARandDenial(string account_ID)
        {
            var account_IDParameter = account_ID != null ?
                new ObjectParameter("Account_ID", account_ID) :
                new ObjectParameter("Account_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Account_Info_for_ARandDenial_Result>("Get_Account_Info_for_ARandDenial", account_IDParameter);
        }
    
        public virtual ObjectResult<Get_AR_Info_for_Balance_Range_Result> Get_AR_Info_for_Balance_Range(Nullable<int> varBalanceRange, Nullable<int> varEntity)
        {
            var varBalanceRangeParameter = varBalanceRange.HasValue ?
                new ObjectParameter("varBalanceRange", varBalanceRange) :
                new ObjectParameter("varBalanceRange", typeof(int));
    
            var varEntityParameter = varEntity.HasValue ?
                new ObjectParameter("varEntity", varEntity) :
                new ObjectParameter("varEntity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_AR_Info_for_Balance_Range_Result>("Get_AR_Info_for_Balance_Range", varBalanceRangeParameter, varEntityParameter);
        }
    
        public virtual int registration(string first_name, string last_name, string middle_name, string email, string phone_number, string pwd)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registration", first_nameParameter, last_nameParameter, middle_nameParameter, emailParameter, phone_numberParameter, pwdParameter);
        }
    
        public virtual int CreateAccount(string first_name, string last_name, string middle_name, string email, string phone_number, string pwd)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAccount", first_nameParameter, last_nameParameter, middle_nameParameter, emailParameter, phone_numberParameter, pwdParameter);
        }
    
        public virtual int Case_Task_InsUpd(Nullable<int> aCT_ID, string aCT_HspAccID, Nullable<int> aCT_ACD_ID, Nullable<bool> aCT_Completed, string aCT_Priority, string aCT_Description, string aCT_Owner, string aCT_Comment, Nullable<System.DateTime> aCT_DueDate, Nullable<int> aCT_DeleteFlag, string aCT_CreatedBy, Nullable<System.DateTime> aCT_CreatedDate, string aCT_UpdatedBy, Nullable<System.DateTime> aCT_Updateddate, string aCT_UpdatedBy_DB, ObjectParameter new_recordNumber)
        {
            var aCT_IDParameter = aCT_ID.HasValue ?
                new ObjectParameter("ACT_ID", aCT_ID) :
                new ObjectParameter("ACT_ID", typeof(int));
    
            var aCT_HspAccIDParameter = aCT_HspAccID != null ?
                new ObjectParameter("ACT_HspAccID", aCT_HspAccID) :
                new ObjectParameter("ACT_HspAccID", typeof(string));
    
            var aCT_ACD_IDParameter = aCT_ACD_ID.HasValue ?
                new ObjectParameter("ACT_ACD_ID", aCT_ACD_ID) :
                new ObjectParameter("ACT_ACD_ID", typeof(int));
    
            var aCT_CompletedParameter = aCT_Completed.HasValue ?
                new ObjectParameter("ACT_Completed", aCT_Completed) :
                new ObjectParameter("ACT_Completed", typeof(bool));
    
            var aCT_PriorityParameter = aCT_Priority != null ?
                new ObjectParameter("ACT_Priority", aCT_Priority) :
                new ObjectParameter("ACT_Priority", typeof(string));
    
            var aCT_DescriptionParameter = aCT_Description != null ?
                new ObjectParameter("ACT_Description", aCT_Description) :
                new ObjectParameter("ACT_Description", typeof(string));
    
            var aCT_OwnerParameter = aCT_Owner != null ?
                new ObjectParameter("ACT_Owner", aCT_Owner) :
                new ObjectParameter("ACT_Owner", typeof(string));
    
            var aCT_CommentParameter = aCT_Comment != null ?
                new ObjectParameter("ACT_Comment", aCT_Comment) :
                new ObjectParameter("ACT_Comment", typeof(string));
    
            var aCT_DueDateParameter = aCT_DueDate.HasValue ?
                new ObjectParameter("ACT_DueDate", aCT_DueDate) :
                new ObjectParameter("ACT_DueDate", typeof(System.DateTime));
    
            var aCT_DeleteFlagParameter = aCT_DeleteFlag.HasValue ?
                new ObjectParameter("ACT_DeleteFlag", aCT_DeleteFlag) :
                new ObjectParameter("ACT_DeleteFlag", typeof(int));
    
            var aCT_CreatedByParameter = aCT_CreatedBy != null ?
                new ObjectParameter("ACT_CreatedBy", aCT_CreatedBy) :
                new ObjectParameter("ACT_CreatedBy", typeof(string));
    
            var aCT_CreatedDateParameter = aCT_CreatedDate.HasValue ?
                new ObjectParameter("ACT_CreatedDate", aCT_CreatedDate) :
                new ObjectParameter("ACT_CreatedDate", typeof(System.DateTime));
    
            var aCT_UpdatedByParameter = aCT_UpdatedBy != null ?
                new ObjectParameter("ACT_UpdatedBy", aCT_UpdatedBy) :
                new ObjectParameter("ACT_UpdatedBy", typeof(string));
    
            var aCT_UpdateddateParameter = aCT_Updateddate.HasValue ?
                new ObjectParameter("ACT_Updateddate", aCT_Updateddate) :
                new ObjectParameter("ACT_Updateddate", typeof(System.DateTime));
    
            var aCT_UpdatedBy_DBParameter = aCT_UpdatedBy_DB != null ?
                new ObjectParameter("ACT_UpdatedBy_DB", aCT_UpdatedBy_DB) :
                new ObjectParameter("ACT_UpdatedBy_DB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Case_Task_InsUpd", aCT_IDParameter, aCT_HspAccIDParameter, aCT_ACD_IDParameter, aCT_CompletedParameter, aCT_PriorityParameter, aCT_DescriptionParameter, aCT_OwnerParameter, aCT_CommentParameter, aCT_DueDateParameter, aCT_DeleteFlagParameter, aCT_CreatedByParameter, aCT_CreatedDateParameter, aCT_UpdatedByParameter, aCT_UpdateddateParameter, aCT_UpdatedBy_DBParameter, new_recordNumber);
        }
    
        public virtual int md_notnull_to_null_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_notnull_to_null_fields", tablenameParameter);
        }
    
        public virtual int md_null_blank_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_null_blank_fields", tablenameParameter);
        }
    
        public virtual int md_null_to_NULL_fields(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("md_null_to_NULL_fields", tablenameParameter);
        }
    
        public virtual int create_user(string first_name, string last_name, string middle_name, string email, string phone_number, string pwd, string role, string keyword, string admin, Nullable<System.Guid> iD)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("First_name", first_name) :
                new ObjectParameter("First_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("Phone_number", phone_number) :
                new ObjectParameter("Phone_number", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("create_user", first_nameParameter, last_nameParameter, middle_nameParameter, emailParameter, phone_numberParameter, pwdParameter, roleParameter, keywordParameter, adminParameter, iDParameter);
        }
    }
}
