//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users_Data
    {
        public System.Guid user_ID { get; set; }


        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required")]
        [DataType(DataType.Text)]
        public string user_first_name { get; set; }


        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        [DataType(DataType.Text)]
        public string user_last_name { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [DataType(DataType.Text)]
        public string user_full_name { get; set; }


        [Display(Name = "Role Key")]
        [Required(ErrorMessage = "Role Key is required")]
        [DataType(DataType.Text)]
        public System.Guid user_role_key { get; set; }

        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number is required")]
        [DataType(DataType.PhoneNumber)]
        public string user_phone_number { get; set; }

        [Display(Name = "Email Id")]
        [Required(ErrorMessage = "Emaild id is required")]
        [DataType(DataType.EmailAddress)]
        public string user_email_id { get; set; }


        [Display(Name = "User Added by")]
        [Required(ErrorMessage = "User Name is required")]
        [DataType(DataType.Text)]
        public string user_added_by { get; set; }


        [Display(Name = "Added Date")]
        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Text)]
        public System.DateTime user_add_date { get; set; }


        [Display(Name = "User Upate Date")]
        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Text)]
        public string user_updated_by { get; set; }
        public Nullable<System.DateTime> user_updated_date { get; set; }


        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required")]
        [DataType(DataType.Text)]
        public byte user_delete_flag { get; set; }




        [Display(Name = "Middle Name")]
        [Required(ErrorMessage = "Middle is required")]
        [DataType(DataType.Text)]
        public string user_middle_name { get; set; }


        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required")]
        [DataType(DataType.Text)]
        public string user_web_pwd { get; set; }
        public string otp_key { get; set; }
        public Nullable<System.DateTime> otp_time { get; set; }
        public byte user_active_flag { get; set; }

        public string confirm_pwd { get; set; }
    }
}
