//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Underpayments_PB
    {
        public string Account { get; set; }
        public string Acct_Class { get; set; }
        public string Acct_Status { get; set; }
        public string Account_Name { get; set; }
        public Nullable<System.DateTime> Disch_Date { get; set; }
        public Nullable<double> Acct_Bal { get; set; }
        public string Message { get; set; }
        public string Diagnosis_Codes__Mapped___CMS_ICD_10_CM___ICD_9_CM_ { get; set; }
        public string Plan_Name { get; set; }
        public string Payor_Name { get; set; }
        public Nullable<double> Allowed_Amount_Difference__Current_NAA_Posted_To_Bucket_ { get; set; }
        public string Expected_Allowed_Amount { get; set; }
        public Nullable<double> Allowed_Amount_Difference__Payor_Specified_ { get; set; }
        public Nullable<int> Underpayment_Reason_Code { get; set; }
        public string Brief_Summary { get; set; }
        public Nullable<System.DateTime> DateOfUpdate { get; set; }
        public string Biller { get; set; }
        public string BillingProvider { get; set; }
        public Nullable<double> TOTALCHARGES { get; set; }
        public Nullable<double> TOTALPAYMENTS { get; set; }
        public Nullable<double> TOTALADJUSTMENTS { get; set; }
        public Nullable<System.DateTime> FIRSTPAYMENTDATE { get; set; }
        public Nullable<double> FIRSTPAYMENTAMT { get; set; }
        public Nullable<System.DateTime> LASTPAYMENTDATE { get; set; }
        public Nullable<double> LASTPAYMENTAMT { get; set; }
        public string CPTCODES { get; set; }
        public Nullable<double> DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
    }
}
