//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Underpayment_ReasonCode1
    {
        public int Reason_Code { get; set; }
        public string Reason_Title { get; set; }
        public string Root_Cause_Category { get; set; }
    }
}
