//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderPayments_PB_July
    {
        public string Account { get; set; }
        public string Acct_Class { get; set; }
        public Nullable<int> Acct_Status { get; set; }
        public string Account_Name { get; set; }
        public string Procedure { get; set; }
        public Nullable<System.DateTime> Svc_Dt { get; set; }
        public Nullable<decimal> Ins_Amt { get; set; }
        public string Billing_Provider { get; set; }
        public string Payor_Name { get; set; }
        public Nullable<decimal> Acct_Bal { get; set; }
        public string Account_Workqueues { get; set; }
        public string All_Claim_Payors { get; set; }
        public Nullable<decimal> Allow_Discrepancy_Amt { get; set; }
        public string Plan_Name { get; set; }
        public string Cur_Plan_Group { get; set; }
        public string Dr_Cr { get; set; }
        public string Dept_Specialty { get; set; }
        public string Diagnosis_Code { get; set; }
        public string Enc_Specialty { get; set; }
        public string Prim_Fee_Sched { get; set; }
        public Nullable<double> Procedure_Code { get; set; }
        public string Procedure_Description { get; set; }
        public Nullable<int> Underpayment_Reason_Code { get; set; }
        public string Brief_Summary { get; set; }
        public Nullable<System.DateTime> DateOfUpdate { get; set; }
        public string ServiceDepartmentName { get; set; }
        public Nullable<System.DateTime> AccountMostRecentClaimDate { get; set; }
        public Nullable<decimal> TotalChargeAmount { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public Nullable<decimal> TotalAdjustmentAmount { get; set; }
        public Nullable<decimal> AllowedAmount_ProfessionalOnly { get; set; }
    }
}
