//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_TCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AR_AGE_CATEGORY
    {
        public string Hospital_Account_ID { get; set; }
        public Nullable<System.DateTime> Admission_Date { get; set; }
        public Nullable<System.DateTime> First_Billed_Date { get; set; }
        public string Age { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Agency { get; set; }
        public Nullable<int> Collectable { get; set; }
        public string Primary_Coverage_Payor_Name { get; set; }
        public Nullable<decimal> Total_Account_Balance { get; set; }
        public string Primary_Coverage_Payor_Financial_Class { get; set; }
        public string Account_AR_Status { get; set; }
        public Nullable<decimal> Total_Primary_Insurance_Balance { get; set; }
        public string Account_Department_Name { get; set; }
        public string Account_Location_Name { get; set; }
        public string Account_Service_Area_Name { get; set; }
        public string Account_Bill_Status { get; set; }
        public string Encounter_Type { get; set; }
        public string Account_Source { get; set; }
    }
}
